name = "EVAERDRAD_storyspin_chara_fanmade"
version = "0.1.0"
authors = ["Bli-AIk"]
description = "Fan-made Chara battle mod inspired by STORYSPIN. A tribute to SSPIN ST's music."

# Resource directories configuration
# 资源目录配置
[resources]
textures = "assets/textures"      # Texture/sprite resources / 图片资源目录
audios = "assets/audios"          # Audio resources / 音频资源目录

[dependencies]
# List dependencies here

[mod_library]
# WASM component file, loaded by wasmtime at runtime
# WASM 组件文件，运行时由 wasmtime 加载
wasm = "mod_example.wasm"

[game]
global_rules = "global.fre.ron"
initial_battle_path = "states/battle/chapters/demo.sequence.ron"
input_config_path = "config/input.ron"
required_modules = ["common", "battle"]
